[package]
name = "ovenauth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
rust-argon2 = "1.0.0"
anyhow = "1.0.51"
actix-identity = "0.4.0"
actix-cors = "0.6.1"
rand = "0.8.4"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
dotenv = "0.15"
chrono = { version = "0.4.19", features = ["serde"] }
url = "2.2.2"
env_logger = "0.9.0"
log = "0.4.14"
uuid = { version = "1.1.1", features = ["v4", "fast-rng"] }
telegram_notifyrs = "0.1.3"
web-push = "0.9.2"
tokio = "1.21.2"
reqwest = { version = "0.11", features = ["json"] }
futures = { version = "0.3.25" }
base64 = { version = "0.13.1" }
itertools = "0.10.5"

[dependencies.sqlx]
version = "0.5.9"
features = ["runtime-actix-rustls", "offline", "json", "postgres" ]
